resolver: lts-15.13

ghc-options: {"$locals": -fwrite-ide-info -fmax-relevant-binds=0}

packages:
  - aura/
  - aur/
  - aursec/

extra-deps:
  - language-bash-0.9.2

nix:
  shell-file: nix/stack.nix
