[package]
name = "aura"
version = "4.0.0-rc1"
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2018"

[dependencies]
alpm = "1.1"
aura-arch = { path = "../aura-arch" }  # TODO Give these versions.
aura-core = { path = "../aura-core" }
chrono = "0.4"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
colored = "2.0"
curl = "0.4"
i18n-embed = { version = "0.12", features = ["fluent-system"] }
i18n-embed-fl = "0.5"
itertools = "0.10"
linya = "0.1"
log = "0.4"
pacmanconf = "0.2"
raur-curl = { path = "../raur-curl" }
rayon = "1.5"
rust-embed = "5.6"
rustyline = "8.0"
serde_json = "1.0"
simplelog = "0.10"
sudo = "0.6"
ubyte = "0.10"
unic-langid = { version = "0.9", features = ["macros"] }
webbrowser = "0.5"

[features]
git = ["alpm/git"]
