[workspace]
members = ["aura", "aura-core", "aura-arch", "aura-common", "raur-curl"]

[patch.crates-io]
# i18n-embed-fl = { git = "https://github.com/fosskers/cargo-i18n", rev = "1f26b5458c75a732fd5b0bd27f88672b2a04b046" }

[profile.release]
lto = true
panic = "abort"
# opt-level = "z"  # Reduces final stripped size by ~20%.
